name: CI

on:
  push:
    branches: [ main ]
  pull_request:

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/rustfmt@v1.1.1
      - name: Format Check
        run: cargo fmt -- --check
      - name: Clippy Check
        run: cargo clippy -- -D warnings
      - name: Test
        run: cargo test --all
